// The spinner line's text for one animation tick: a phrase for what the turn
// is doing, resolving out of noise when it changes, and a scanning bar. The
// phrases are science-fiction references, each filed under the state its
// plain sense reads as at a glance.

export type SpinnerMode = 'requesting' | 'responding' | 'thinking' | 'tool-input' | 'tool-use'

export const SPINNER_PHRASES: Readonly<Record<SpinnerMode, readonly string[]>> = {
  requesting: [
    'Jacking in',
    'Opening the uplink',
    'Handshaking',
    'Tightbeaming the request',
    'Opening a tightbeam',
    'Hailing the Rocinante',
    'Raising Tycho Station',
    'Hailing beltalowda',
    'Opening hailing frequencies',
    'Calling the operator',
    'Dialing the Nebuchadnezzar',
    'Diving the net',
    'Hailing Section 9',
    'Entering the Grid',
    'Pinging the mothership',
    'Requesting docking clearance',
    'Requesting to know more',
    'Needlecasting in',
    'Phoning home',
    'Establishing a secure bind',
    'Jacking into cyberspace',
    'Hailing Wintermute',
    'Goggling into the Metaverse',
    'Entering the Black Sun',
    'Tapping the Feed',
    'Waking the Primer',
    'Calling the worm',
    'Hailing the Guild',
    'Opening the ansible',
    'Farcasting in',
    'Dialing the gate',
    'Hailing Galactica Actual',
    'Hailing on the Codec',
    'Initiating neural handshake',
    'Entering the Drift',
    'Presenting the multipass',
    'Calling Batou',
    'Hailing White Base',
    'Hailing the SDF-1',
    'Hailing Skull Leader',
    'Uplinking to Cyberdyne',
    'Hailing Skynet',
    'Requesting clothes and boots',
    'Sending recognition codes',
  ],
  thinking: [
    'Cracking the cipher',
    'Reading the black box',
    'Overclocking',
    'Listening to my ghost',
    'Consulting the Tachikomas',
    'Asking the Puppet Master',
    'Deep diving',
    'Dreaming of electric sheep',
    'Reading the digital rain',
    'Contemplating the spoon',
    'Learning kung fu',
    'Consulting the Oracle',
    'Freeing my mind',
    'Seeing the code',
    'Plotting the burn',
    'Understanding the bug',
    'Trusting Envoy intuition',
    'Reading the cortical stack',
    'Asking Poe',
    'Computing forty-two',
    'Asking Deep Thought',
    'Running Mentat computations',
    'Consulting the Three Laws',
    'Calculating the odds',
    'Calculating the jump',
    'Plotting a course',
    'Decrypting',
    'Decoding the transmission',
    'Asking the Dixie Flatline',
    'Consulting the Hosaka',
    'Asking the Librarian',
    'Listening to Reason',
    'Reading the Primer',
    'Puzzling out Castle Turing',
    'Weighing plans within plans',
    'Seeing the Golden Path',
    'Consulting prescience',
    'Consulting the Prime Radiant',
    'Computing psychohistory',
    'Consulting the TechnoCore',
    'Consulting a ship Mind',
    'Checking for gravitas',
    'Finding the enemy\'s gate',
    'Consulting MU-TH-UR',
    'Reviewing prime directives',
    'Querying the ship computer',
    'Consulting the Guide',
    'Thinking with portals',
    'Asking Cortana',
    'Consulting the precogs',
    'Going a level deeper',
    'Checking the totem',
    'Reading heptapod logograms',
    'Assessing the threat',
    'Recognizing a UNIX system',
    'Consulting the Codex',
    'Awakening as a Newtype',
    'Sensing a Newtype flash',
    'Decoding protoculture',
    'Reading the HUD',
    'Checking the neural net CPU',
    'Consulting the Hybrid',
    'Charting the way to Earth',
  ],
  'tool-input': [
    'Calibrating',
    'Compiling the payload',
    'Arming the daemon',
    'Forging the packet',
    'Booting the deck',
    'Compiling the icebreaker',
    'Slotting the chip',
    'Loading the quickhack',
    'Loading the Construct',
    'Loading a pilot program',
    'Loading the jump program',
    'Loading guns, lots of guns',
    'Priming the thermoptics',
    'Prepping for the drop',
    'Suiting up',
    'Hitting the crash couch',
    'Loading the PDCs',
    'Charging the railgun',
    'Warming up the reactor',
    'Checking the suit seals',
    'Prepping the Roci',
    'Prepping a fresh sleeve',
    'Priming the neurachem',
    'Spooling up the FTL drive',
    'Setting the jump coordinates',
    'Charging the capacitors',
    'Booting the Ono-Sendai',
    'Slotting the Kuang virus',
    'Slotting a microsoft',
    'Compiling the nam-shub',
    'Priming the matter compiler',
    'Rallying the Mouse Army',
    'Setting the thumper',
    'Donning the stillsuit',
    'Raising the Holtzman shield',
    'Setting phasers to stun',
    'Raising shields',
    'Locking S-foils',
    'Grabbing my towel',
    'Raising the sync ratio',
    'Getting in the robot',
    'Locking chevron seven',
    'Charging the flux capacitor',
    'Setting humor to 75 percent',
    'Unfolding a sophon',
    'Appeasing the machine spirit',
    'Reciting rites of activation',
    'Raising the attack barrier',
    'Feeding the Tachikomas oil',
    'Prepping the mobile suit',
    'Loading the catapult deck',
    'Drawing the beam saber',
    'Charging the reflex cannon',
    'Spooling the fold drive',
    'Switching to Battloid mode',
    'Setting CPU to read/write',
    'Reloading the shotgun',
    'Setting Condition One',
  ],
  'tool-use': [
    'Administering Voight-Kampff',
    'Running a baseline test',
    'Checking doors and corners',
    'Lighting the Epstein drive',
    'Rerouting power',
    'Reversing the polarity',
    'Probing the net',
    'Riding the wire',
    'Walking the stack',
    'Sweeping the ports',
    'Tunneling',
    'Breaking the ICE',
    'Riding the simstim',
    'Running the shadows',
    'Slicing the firewall',
    'Hacking the Gibson',
    'Running Breach Protocol',
    'Executing the quickhack',
    'Pulling the data shard',
    'Sending in the Tachikomas',
    'Bug hunting',
    'Killing bugs',
    'Doing my part',
    'Making the drop',
    'Deploying Mobile Infantry',
    'Burning hard',
    'Firing the PDCs',
    'Clearing the room',
    'Running on neurachem',
    'Watching the motion tracker',
    'Making it so',
    'Punching it',
    'Jumping to lightspeed',
    'Staying on target',
    'Making the Kessel Run',
    'Letting the spice flow',
    'Running Kuang Mark Eleven',
    'Cutting black ICE',
    'Raiding Sense/Net',
    'Storming Straylight',
    'Running the matter compiler',
    'Compiling from the Feed',
    'Unleashing the Mouse Army',
    'Riding the sandworm',
    'Walking without rhythm',
    'Folding space',
    'Harvesting the spice',
    'Crossing the deep desert',
    'Searching the Jedi archives',
    'Running a level 3 diagnostic',
    'Scanning with the tricorder',
    'Energizing',
    'Giving her all she\'s got',
    'Opening the pod bay doors',
    'Keeping Serenity flying',
    'Drilling in the Battle Room',
    'Displacing a knife missile',
    'Engaging Improbability Drive',
    'Waving the sonic screwdriver',
    'Fighting for the Users',
    'Chasing the bounty',
    'Finishing the fight',
    'Testing, for science',
    'Sneaking in a cardboard box',
    'Hitting 88 miles per hour',
    'Crossing the streams',
    'Hacking the planet',
    'Sciencing the shit out of it',
    'Looping the day',
    'Purging the heresy',
    'Breaching the attack barrier',
    'Scanning the cyberbrain',
    'Chasing the Laughing Man',
    'Launching the Gundam',
    'Firing the beam rifle',
    'Spreading Minovsky particles',
    'Going three times faster',
    'Dropping the colony',
    'Activating Trans-Am',
    'Scrambling the Veritechs',
    'Executing a space fold',
    'Pulling a Daedalus Maneuver',
    'Firing the main gun',
    'Terminating the target',
    'Displacing through time',
    'Hunting Sarah Connor',
    'Launching the alert Vipers',
    'Jumping the fleet',
    'Rolling the hard six',
    'Running the Adama Maneuver',
    'Checking for Cylons',
  ],
  responding: [
    'Uploading the take',
    'Piping the feed',
    'Tightbeaming the reply',
    'Broadcasting to the Belt',
    'Making it clear, sasa ke?',
    'Needlecasting the reply',
    'Printing the readout',
    'Rendering the hologram',
    'Transmitting on all bands',
    'Filing the after-action',
    'Writing the debrief',
    'Letting you know more',
    'Reporting to the Major',
    'Whispering back',
    'Surfacing with the answer',
    'Recording the captain\'s log',
    'Beaming it down',
    'Sending the Death Star plans',
    'Delivering the pizza',
    'Reporting to Armitage',
    'Uploading intel to the CIC',
    'Handing over the hypercard',
    'Racting the reply',
    'Writing on mediatronic paper',
    'Speaking with the Voice',
    'Broadcasting on the ansible',
    'Filing the Guide entry',
    'Transmitting to Starfleet',
    'Logging the sol entry',
    'Briefing Aramaki',
    'Reporting to Bright',
    'Reporting to Captain Gloval',
    'Singing like Minmei',
    'Saying hasta la vista',
    'Promising I\'ll be back',
    'Giving the thumbs up',
    'Reporting to the CIC',
    'Saying so say we all',
    'Citing the Codex Astartes',
  ],
}

const NOISE = '▓▒░█#%&@$01<>/=+'
// Characters resolved per tick while a phrase decrypts.
const REVEAL_RATE = 2
// Once resolved, one character flickers back to noise every this many ticks.
const GLITCH_PERIOD = 23
const BAR_CELLS = 6

function greatestCommonDivisor(a: number, b: number): number {
  return b === 0 ? a : greatestCommonDivisor(b, a % b)
}

// A step through a pool of `size` that visits every entry before repeating
// one, and does not simply walk the list in the order it is written.
function strideFor(size: number): number {
  return [31, 37, 41, 43].find(stride => greatestCommonDivisor(stride, size) === 1) ?? 1
}

// The phrase for a mode at one pick. The caller keeps a pick per mode and
// advances it each time the turn enters that mode, so `size` picks in a row
// show every phrase of the pool once.
export function phraseFor(mode: SpinnerMode, pick: number): string {
  const phrases = SPINNER_PHRASES[mode]
  const index = Number.isFinite(pick) ? Math.abs(Math.trunc(pick)) : 0

  return phrases[(index * strideFor(phrases.length)) % phrases.length] ?? phrases[0] ?? ''
}

function noiseAt(tick: number, index: number): string {
  return NOISE[(tick * 7 + index * 13) % NOISE.length] ?? '#'
}

// `age` is the ticks since this phrase came up: it decrypts left to right.
export function decrypt(phrase: string, age: number, tick: number): string {
  const revealed = age * REVEAL_RATE
  const isResolved = revealed >= phrase.length
  const glitchAt = isResolved && tick % GLITCH_PERIOD === 0 ? (tick / GLITCH_PERIOD) * 5 % phrase.length : -1

  return [...phrase]
    .map((character, index) => {
      const isNoise = character !== ' ' && (index >= revealed || index === glitchAt)

      return isNoise ? noiseAt(tick, index) : character
    })
    .join('')
}

// A two-cell block that sweeps the bar and bounces off its ends.
export function scanBar(tick: number): string {
  const span = BAR_CELLS - 2
  const step = tick % (span * 2)
  const start = step <= span ? step : span * 2 - step

  return Array.from({ length: BAR_CELLS }, (_, index) =>
    index === start || index === start + 1 ? '▰' : '▱',
  ).join('')
}
